version: 0.1
log:
  fields:
    service: registry
storage:
  azure:
    accountname: qainsregistry
    accountkey: Ze3WNaV9lgq2aVb0sP1jL/phAPQyG4/tIEAnxOWQhqs4g8uXS5oBt7/Gl7zelFappk0vMz3iehOSplgfOng4Vg==
    container: registry
auth:
  htpasswd:
    realm: qainstructor-registry
    path: /etc/docker/registry/htpasswd
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
