version: '2'
services:
  faye:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/faye:0.0.1

  postgres:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/postgres:0.0.1
    volumes:
      - qainstructor-db:/var/lib/postgresql/data

  backup:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/backup:0.0.1
    links:
      - postgres

  redis:
    extends:
      file: docker-compose.common.yml
      service: service
    image: redis:3.2.4

  selenium-server:
    extends:
      file: docker-compose.common.yml
      service: service
    image: selenium/standalone-firefox:2.53.1

  sample-app:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/sample-app:latest
    volumes:
      - qainstructor-sample-app-assets:/assets-volume

  nginx:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/nginx:0.0.3
    links:
      - rails
      - sample-app
      - faye
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - qainstructor-engine-assets:/app/public
      - qainstructor-sample-app-assets:/sample-app/public

  rails:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/engine:latest
    command: ["bundle", "exec", "puma", "-b", "tcp://0.0.0.0", "-p", "8080", "--pidfile", "/tmp/puma.pid", "-t", "8", "-w", "2"]
    links:
      - postgres
      - redis

  sidekiq:
    extends:
      file: docker-compose.common.yml
      service: service
    image: qainstructor.com:5043/qainstructor/engine:latest
    command: [bundle, exec, sidekiq]
    links:
      - faye
      - postgres
      - redis
      - selenium-server
    # sidekiq container should be able to start docker containers using host docker.sock file
    # also, it's important that job files inside container should share the host dir, otherwise
    # volumes won't work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  qainstructor-db:
    external: true
  qainstructor-engine-assets:
    external: true
  qainstructor-sample-app-assets:
    external: true
