sidekiq:
  dns: ["192.168.1.238"]
  env_file:
    - ./env/development.env
  volumes:
    - ./engine:/app
    - /Users/jobs:/Users/jobs

selenium-server:
  dns: ["192.168.1.238"]

rails:
  env_file:
    - ./env/development.env
  volumes:
    - ./engine:/app
