version: '2'
services:
  postgres:
    env_file:
      - ./env/development.env

  selenium-server:
    links:
      - nginx

  nginx:
    env_file:
      - ./env/development.env
    networks:
      default:
        aliases:
          - app.sample.lvh.me
          - bomb.sample.lvh.me
          - secret.sample.lvh.me
          - slow.sample.lvh.me

  sidekiq:
    env_file:
      - ./env/development.env
    volumes:
      - ./engine:/app
      - /Users/jobs:/Users/jobs

  rails:
    env_file:
      - ./env/development.env
    volumes:
      - ./engine:/app
      - /Users/jobs:/Users/jobs
      - /var/run/docker.sock:/var/run/docker.sock # We need this to run specs
