source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'

# error reporting
gem 'rollbar', '~> 2.5.0'

# Frontend gems
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'slim-rails'

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'js-routes'
gem 'ng-rails-csrf'

source 'https://rails-assets.org' do
  gem 'rails-assets-highlightjs'
  gem 'rails-assets-angular'
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-jasny-bootstrap'
  gem 'rails-assets-animate-css'
  gem 'rails-assets-remarkable-bootstrap-notify'
  gem 'rails-assets-videojs'
end

gem 'devise'

# needed for sidekiq web ui
gem 'sinatra', :require => nil
gem 'sidekiq'

gem 'fog'
gem 'carrierwave', '~> 0.5'
gem 'aws-sdk', '~> 2'

gem 'unicorn'

gem 'activeadmin', github: 'activeadmin'
gem 'has_secure_token'
gem 'active_model_serializers'
gem 'draper', '~> 2.0'
gem 'pundit'

# used to create new sessions for $selenium connection pool
gem 'connection_pool'
gem 'selenium-webdriver'

gem 'faye'

gem 'stripe'

gem 'docker-api'

group :development, :test do
  gem 'byebug'
  gem 'rspec-rails', '~> 3.0'
end

group :development do
  gem 'spring'
  gem 'spring-commands-rspec'

  gem 'web-console', '~> 2.0'
  gem 'quiet_assets'
end

group :test do
  gem 'shoulda-matchers', require: false
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'simplecov', :require => false
  gem 'mutant-rspec'
  gem 'webmock'
  gem 'vcr'
end

gem 'puma'
