# http is used for a reason - bundle install errors out on Azure when run inside Docker
source 'http://rubygems.org'

gem 'syntax' # for cucumber output syntax highlighting
gem 'cucumber'
gem 'selenium-webdriver', '2.49.0.dev'
gem 'rspec'
